###
POST http://localhost:5000/api/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "Laurence",
    "password": "Pass123@",
    "name": "Laurence Cortez",
    "email": "laurencecortez27.lc@gmail.com",
    "age": "22"
}

################################
GET http://localhost:5000/api/users HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NTYwYmMwLWMzMmUtNGY4ZC05NTM5LTA1YmQyNzZjYTk3NCIsImVtYWlsIjoibGF1cmVuY2Vjb3J0ZXoyNi5sY0BnbWFpbC5jb20iLCJpYXQiOjE2NTkyNjY1NjEsImV4cCI6MTY1OTI2NzQ2MX0.tjfZS7ywyzGHUfuFE9hcIwXtfeb4i1--dlDvwJRd8WgwpW-Xyz3gcfe2QnSXjtyfGaW1OyyhO3eRr7AKr3VjvsdBzEDQcDcjpmqxkI5WddFWaQm-T5FYJGWYhDEI8--ntL5Jw2UjIWCsHvmB3OWrOeBWmJ21IkLf4IswILSx5Qw-G4b0Dkp856eGCryRzRVYRmKOp0M1LqFnzn8757sxCJsomf28PmE7D91djXwhOZo5EZKsdbgjMZ3r5RTpC4tLuT_wXwS5gjqmeaz0vuHlv4uxqFxiAcu2M_QFeZMQoXHU3zfzPcWOzQ4v5uZ2LZr7jDh8jQ_mplLd0gz-syRPQST0qoXwMabIewE3Bb4G2VzJr_AVdH4torlo5ovKm7R68Mh2_n7giQT-pDa3D84d0GvnONEjOPzamOgwUqf3y-D3WQba8ppPTob3pDhtsF_o31i5D3azKNNZldBqewLYCVKM8EUyjtD6oPf7t9U3qjfoqN280DYR-R-SP8_3thJMXSw0k8hhKytBQHcJwTlS3yhbK8H_7ofobFNmjymHsiRtEXkbWef-qIJdC7hmw-_QJ2YIU-dl_PquPZKo9vgGpjQYdTUjD8mC5YOcLCiFgkrVZG8TXSnzlqhzx69P3ua3l-EB5AZbJ8045agswYBbVIJZitAavQUZh7vIbwaMIOo
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NTYwYmMwLWMzMmUtNGY4ZC05NTM5LTA1YmQyNzZjYTk3NCIsImVtYWlsIjoibGF1cmVuY2Vjb3J0ZXoyNi5sY0BnbWFpbC5jb20iLCJpYXQiOjE2NTkyNjY1NjEsImV4cCI6MTY2MTg1ODU2MX0.Wubl46R6KzOVHhGcjieWpJQ8jo7Vpsz_tCTz1VV8LowVD9e56sbmIWVW1HHO3wRTJBa_bc1rM5CYYogdwnyjGni8ZsNu6dnKRkiC_HvmqeaYKESHJbBYAD95HUmFTwO1Ck39JWcyQ6PLhoR11z6NXR11tbm7sTEdolMwj7adMXsgSwBMHImRlNzr6_lW8861M9qw13BwSaYFBSaDFb15vO-u-1ws7iTwQsnfab3jfPoRGOwBHHb1W5AIm1M3FlxUinQPuJB2p4F2cL8MpS1i3kUPkaMiPYr5PIXuFR_ukbua5uerSiOvJ4SK9kID0bzXbjBum27QOVjI-03J_zz7YVgm4kIzouNgi7iOAx4GF2Yq744MqHnehieRO311NtIF3BT0Ud7ItLSeKqwuxz89aggqP1r_Pg6BI5Vmvt_lZruFtDV8LU4Id7S3T0ZXDshA9E16HwrjHFKzysWqWU2Glzk2srvFe-w2EJPw3Ssvk6PORUYDmZp_EPkHk0jIdj_MiLhUINFcz2eWfz_dETb4XppJkrw0zUiOb-JaZycq_vuj4feXI6v5EmF7gRmJJnhJjxdUd4uT7ikVbnQLVAyjq77qzZ8inyXnjj7FrlfdjaajeSdPB_ruL69zRshTpKlMnVly6rAnLRa5lULCbHBe2ET3w99byaaGqMhkwI9yZ4k
################################
DELETE http://localhost:5000/api/user/logout HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NTYwYmMwLWMzMmUtNGY4ZC05NTM5LTA1YmQyNzZjYTk3NCIsImVtYWlsIjoibGF1cmVuY2Vjb3J0ZXoyNi5sY0BnbWFpbC5jb20iLCJpYXQiOjE2NTkyNjY1NjEsImV4cCI6MTY1OTI2NzQ2MX0.tjfZS7ywyzGHUfuFE9hcIwXtfeb4i1--dlDvwJRd8WgwpW-Xyz3gcfe2QnSXjtyfGaW1OyyhO3eRr7AKr3VjvsdBzEDQcDcjpmqxkI5WddFWaQm-T5FYJGWYhDEI8--ntL5Jw2UjIWCsHvmB3OWrOeBWmJ21IkLf4IswILSx5Qw-G4b0Dkp856eGCryRzRVYRmKOp0M1LqFnzn8757sxCJsomf28PmE7D91djXwhOZo5EZKsdbgjMZ3r5RTpC4tLuT_wXwS5gjqmeaz0vuHlv4uxqFxiAcu2M_QFeZMQoXHU3zfzPcWOzQ4v5uZ2LZr7jDh8jQ_mplLd0gz-syRPQST0qoXwMabIewE3Bb4G2VzJr_AVdH4torlo5ovKm7R68Mh2_n7giQT-pDa3D84d0GvnONEjOPzamOgwUqf3y-D3WQba8ppPTob3pDhtsF_o31i5D3azKNNZldBqewLYCVKM8EUyjtD6oPf7t9U3qjfoqN280DYR-R-SP8_3thJMXSw0k8hhKytBQHcJwTlS3yhbK8H_7ofobFNmjymHsiRtEXkbWef-qIJdC7hmw-_QJ2YIU-dl_PquPZKo9vgGpjQYdTUjD8mC5YOcLCiFgkrVZG8TXSnzlqhzx69P3ua3l-EB5AZbJ8045agswYBbVIJZitAavQUZh7vIbwaMIOo
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NTYwYmMwLWMzMmUtNGY4ZC05NTM5LTA1YmQyNzZjYTk3NCIsImVtYWlsIjoibGF1cmVuY2Vjb3J0ZXoyNi5sY0BnbWFpbC5jb20iLCJpYXQiOjE2NTkyNjY1NjEsImV4cCI6MTY2MTg1ODU2MX0.Wubl46R6KzOVHhGcjieWpJQ8jo7Vpsz_tCTz1VV8LowVD9e56sbmIWVW1HHO3wRTJBa_bc1rM5CYYogdwnyjGni8ZsNu6dnKRkiC_HvmqeaYKESHJbBYAD95HUmFTwO1Ck39JWcyQ6PLhoR11z6NXR11tbm7sTEdolMwj7adMXsgSwBMHImRlNzr6_lW8861M9qw13BwSaYFBSaDFb15vO-u-1ws7iTwQsnfab3jfPoRGOwBHHb1W5AIm1M3FlxUinQPuJB2p4F2cL8MpS1i3kUPkaMiPYr5PIXuFR_ukbua5uerSiOvJ4SK9kID0bzXbjBum27QOVjI-03J_zz7YVgm4kIzouNgi7iOAx4GF2Yq744MqHnehieRO311NtIF3BT0Ud7ItLSeKqwuxz89aggqP1r_Pg6BI5Vmvt_lZruFtDV8LU4Id7S3T0ZXDshA9E16HwrjHFKzysWqWU2Glzk2srvFe-w2EJPw3Ssvk6PORUYDmZp_EPkHk0jIdj_MiLhUINFcz2eWfz_dETb4XppJkrw0zUiOb-JaZycq_vuj4feXI6v5EmF7gRmJJnhJjxdUd4uT7ikVbnQLVAyjq77qzZ8inyXnjj7FrlfdjaajeSdPB_ruL69zRshTpKlMnVly6rAnLRa5lULCbHBe2ET3w99byaaGqMhkwI9yZ4k
################################
POST http://localhost:5000/api/user/refresh HTTP/1.1
x-auth-token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NTYwYmMwLWMzMmUtNGY4ZC05NTM5LTA1YmQyNzZjYTk3NCIsImVtYWlsIjoibGF1cmVuY2Vjb3J0ZXoyNi5sY0BnbWFpbC5jb20iLCJpYXQiOjE2NTkyNjY1NjEsImV4cCI6MTY1OTI2NzQ2MX0.tjfZS7ywyzGHUfuFE9hcIwXtfeb4i1--dlDvwJRd8WgwpW-Xyz3gcfe2QnSXjtyfGaW1OyyhO3eRr7AKr3VjvsdBzEDQcDcjpmqxkI5WddFWaQm-T5FYJGWYhDEI8--ntL5Jw2UjIWCsHvmB3OWrOeBWmJ21IkLf4IswILSx5Qw-G4b0Dkp856eGCryRzRVYRmKOp0M1LqFnzn8757sxCJsomf28PmE7D91djXwhOZo5EZKsdbgjMZ3r5RTpC4tLuT_wXwS5gjqmeaz0vuHlv4uxqFxiAcu2M_QFeZMQoXHU3zfzPcWOzQ4v5uZ2LZr7jDh8jQ_mplLd0gz-syRPQST0qoXwMabIewE3Bb4G2VzJr_AVdH4torlo5ovKm7R68Mh2_n7giQT-pDa3D84d0GvnONEjOPzamOgwUqf3y-D3WQba8ppPTob3pDhtsF_o31i5D3azKNNZldBqewLYCVKM8EUyjtD6oPf7t9U3qjfoqN280DYR-R-SP8_3thJMXSw0k8hhKytBQHcJwTlS3yhbK8H_7ofobFNmjymHsiRtEXkbWef-qIJdC7hmw-_QJ2YIU-dl_PquPZKo9vgGpjQYdTUjD8mC5YOcLCiFgkrVZG8TXSnzlqhzx69P3ua3l-EB5AZbJ8045agswYBbVIJZitAavQUZh7vIbwaMIOo
Cookie: refresh-token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ1NTYwYmMwLWMzMmUtNGY4ZC05NTM5LTA1YmQyNzZjYTk3NCIsImVtYWlsIjoibGF1cmVuY2Vjb3J0ZXoyNi5sY0BnbWFpbC5jb20iLCJpYXQiOjE2NTkyNjY1NjEsImV4cCI6MTY2MTg1ODU2MX0.Wubl46R6KzOVHhGcjieWpJQ8jo7Vpsz_tCTz1VV8LowVD9e56sbmIWVW1HHO3wRTJBa_bc1rM5CYYogdwnyjGni8ZsNu6dnKRkiC_HvmqeaYKESHJbBYAD95HUmFTwO1Ck39JWcyQ6PLhoR11z6NXR11tbm7sTEdolMwj7adMXsgSwBMHImRlNzr6_lW8861M9qw13BwSaYFBSaDFb15vO-u-1ws7iTwQsnfab3jfPoRGOwBHHb1W5AIm1M3FlxUinQPuJB2p4F2cL8MpS1i3kUPkaMiPYr5PIXuFR_ukbua5uerSiOvJ4SK9kID0bzXbjBum27QOVjI-03J_zz7YVgm4kIzouNgi7iOAx4GF2Yq744MqHnehieRO311NtIF3BT0Ud7ItLSeKqwuxz89aggqP1r_Pg6BI5Vmvt_lZruFtDV8LU4Id7S3T0ZXDshA9E16HwrjHFKzysWqWU2Glzk2srvFe-w2EJPw3Ssvk6PORUYDmZp_EPkHk0jIdj_MiLhUINFcz2eWfz_dETb4XppJkrw0zUiOb-JaZycq_vuj4feXI6v5EmF7gRmJJnhJjxdUd4uT7ikVbnQLVAyjq77qzZ8inyXnjj7FrlfdjaajeSdPB_ruL69zRshTpKlMnVly6rAnLRa5lULCbHBe2ET3w99byaaGqMhkwI9yZ4k

################################
post http://localhost:5000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "Laurence33",
    "password": "Pass123@"
}

